# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE=moveit.rosinstall
    - TEST_BLACKLIST=moveit_ros_perception  # mesh_filter_test fails due to broken Mesa OpenGL
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-function"
    - WARNINGS_OK=false
      # Coverity scan:
      # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
      #   via the "travis encrypt" command using the project repo's public key
    - secure: "eCUhz17hdQYfuQI9v+I5nWa5Lja97otSdABh9BgF57LIOz9+Ycx5xVMU1iGhUlM6wDJMhlrRyuAkqoo/oiMqzwAn+0+2bn/lVpWGUF3Kb5vfDgYqp2OcpMn1PBEM0pp9wLwIHrN/nthE0a1zAN3Vwnd8OoWYNq9Dw8/rcN6JcYUuD/zu8o/WJJenFfq076tzFr4IEYFgzElxUWQw4lIx4qFVZ2N1FygtwZCZBBNkllKDIvGsJNaB9elJGGG2bpWqy62HhlETrWPp5XLb63xYHq5JX4rlmT5HosHaox3bqrHuToxtyoleuuEnFdhZ2ywCICQVuOKHP9O+uzPvqBGxT60Jr0vAJIDV8g/OOQn85cSHL4FcXyt1zslLSmfR9+wf619719SzQjGWbT3hdNRCDOKnZdA+ADva2nNIPl4f/qWniuSrSqtDeOLko++m+/sH/KumhoyORD2Fs7g0zr3hAQYKttaMXw6vkKU8d02ha+n5/qGNvaZ1vF84gG9/fowdobrwuirPaJn7h5yImkmeA1DC+63eN38dYv9KhX9uC409uSZYs1QqLiQv3VIlKxoafvOHvXvMI1r7zdR8VgX8WmXHyN4t3B6fPPgD7M0zYVkoJR0j4qxUDxw5k5avJxjkSdbg7Ss3s6Gy8BhFHgfYNyKhBBlFeeyf8OnFVsV2ELg="

  matrix:
#    - ROS_DISTRO=kinetic
#    - TEST="clang-format catkin_lint"
    - ROS_DISTRO=melodic

matrix: # Add a separate config to the matrix, using clang as compiler
  include:
    # add a config to the matrix using clang as compiler and also test ikfast plugin creation
    - compiler: gcc
      env: ROS_REPO=ros-shadow-fixed
           BEFORE_DOCKER_SCRIPT="source moveit_kinematics/test/test_ikfast_plugins.sh"
           CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-function -Wno-overloaded-virtual"
      branches:
        only:
        - melodic-devel
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "max-krichenbauer/moveit"
            description: "The MoveIt! Motion Planning Framework"
          notification_email: max@marui-plugin.com
          build_command_prepend: "git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci"
          # ^ should already be cloned to that location by before_script
          # build_command: "./travis_coverity.sh"
          build_command: "cov-build --dir cov-int .moveit_ci/travis.sh"
          branch_pattern: melodic-devel

  fast_finish: true  # finish, even if allow-failure-tests still running

# before_script:
#   - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

# script:
#   - .moveit_ci/travis.sh

